language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  - COMPOSER_MEMORY_LIMIT=-1 COMPOSER_MIRROR_PATH_REPOS=1
before_install:
  - cd ~
  - composer create-project chirripo/drupal-template testchirripo --stability stable --no-interaction
  - cd testchirripo
  - echo "PROJECT_ROOT=~/testchirripo" >> .env
  - composer install
  - cd $TRAVIS_BUILD_DIR
  - composer install
before_script:
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
script:
  - cd ~/testchirripo
  - chirripo-proxy --version
  - chirripo-proxy list
  - chirripo-proxy up
  - chirripo-proxy down
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - ./box.phar build
  - sha1sum chirripo-proxy.phar > chirripo-proxy.version
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: HOYNxhuelssd4uinQkTykij3j45w4wpZ3fOGpFUAK7hGRa13EZFrLpKwhSCLGKkjATAJuk7WmOWYM0540tTrzuDVJg3O4bLx6hFfa3TVXBK3U7r6XB2TvV1tfD25w8BQprrwl6MEso/WeXaB0gEslAqOXMh7huBIkVBL4ac+ppAs7SNn3E3ZAwiRlKvPJLVTLAoSEoqJo/zxs+uUxcYwSztwUmotlDMWOErdBgF1NAUkRpgoD1DRHvI7tGjy21q5SZr9zbBW8OuP8h8i2vvMQ8TyqUAsuaEB/eJY33FBSiH8DiuW862pgkWyusz2nZRcvO3rBdbJh/5dCMQ8GXTf0O+E9vaVcF94vrqgVL5ZnznWSbbVvGB6ZYJ3kUMehAbJ7Qf0AWETzhJ+1fsd/u6YNuydqmM3NV9gTKJKLW33VYGPXbKZP86gOlscSd7Mtrg251/GHDh0EpXBMw7xI74ZL0oLcp1ixSdjw+w+VP3kiAUwKZ2chnlTwP1E1RZNEB3f2UReqJnFERoKz20NA3w6Qw0cIExEmdHRmZLaZ5UtNsNa91Xp5xrHgInEueoErqZGF2NkyC0QMyKIGvFqI+PxZ08CyDe2D00n1Hlm/EG1ojkUUIzFgkX9kss+2xLX6JBUcHtt75XSrZkMINsReBsCXkFQOJd5LHRIJzW2/WtPUn4=
  file:
    - chirripo-proxy.phar
    - chirripo-proxy.version
  on:
    repo: chirripo/chirripo-proxy
    tags: true
