language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  - COMPOSER_MEMORY_LIMIT=-1 COMPOSER_MIRROR_PATH_REPOS=1
before_install:
  - cd ~
  - composer create-project chirripo/drupal-template testchirripo --stability stable --no-interaction
  - cd testchirripo
  - echo "PROJECT_ROOT=~/testchirripo" >> .env
  - composer install
  - cd $TRAVIS_BUILD_DIR
  - composer install
before_script:
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
script:
  - cd ~/testchirripo
  - chirripo-proxy --version
  - chirripo-proxy list
  - chirripo-proxy up
  - chirripo-proxy down

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - ./box.phar build
  - sha1sum chirripo-proxy.phar > chirripo-proxy.version

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kYbMenPE4yfmpDkOIlyfojPishC9XIKWq2NiidZ4sZNhoXIYFhmN1bDPYLrXOhKL+s3b9Q8UaJDduZM0i8k59ZcZCz2M3aG+oVD812SuZFE5jtQOej+YbcGfEP6qKMr/vEQOqfcHEpQZAif9BGiD3IZ325hYrRUCh6hqUApS1xXjLX6ZfxNCdS0+9Li7uwF1LoE6GCy8pJ1kcGkRUN/K5lP8IOgmtIKzb88Gb9NySdie4M9EBC4Eh5PJpCP9052lnd0ZrsbGireVbJfWlXy3MVp4olt5gTb6EghbGvsd6Cs6re7w+c+5bPfn//6ZopLVwL96mPnIvTCdSOLvprO6stoH6MG/KbPCB86RNFloTD7jK6T2maExShOYoJrfS1/G0wkLv9l/goPy3ZdIJSg2++yhhrM4HlTaszZZte3RFqty1fzM5mahO1Z5sCtfXJSle2WKais14/47CAoz3D5YvAtGYGIEUHKJajveG1pqUMBi/5urTdu+6EJO/YF/me5Zhniiy0fWi3UGIcULibxhVmqIH8nwYzQOi7BGLRV7JM3rD1xABPHpxzgobCE5CYfUBEdLZPrBpql/XFtuwXXjZPTeiEy5pg7y2zBg6D8avJ7WGqV9aL97F/iYup24WTpOFIx9qiGYpD1V6D1gBFKlj1rf9VEjF5/sOi7OEE/VVRM=
  file:
    - chirripo-proxy.phar
    - chirripo-proxy.version
  on:
    repo: chirripo/chirripo-proxy
    tags: true