version: "3.6"

services:
  proxy:
    image: "traefik:v2.2"
    container_name: "chirripo_proxy"
    command:
      - --entrypoints.web.address=:${CHIRRIPO_PROXY_PORT}
      - --providers.docker=true
      - --api.insecure
    ports:
      - "${CHIRRIPO_PROXY_PORT}:80"
      - "${CHIRRIPO_PROXY_DASHBOARD_PORT}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - chirripo_proxy

networks:
  chirripo_proxy:
    external: true